### PR TITLE
Fix ISSUE 588. and ISSUE 589

### LINKED ISSUE #588: [User Bug Report] - Some HEK frm breaking event marker selection
**Describe the bug**
Some HEK frm breaking the event marker selection

**To Reproduce**
1. Go to 'https://helioviewer.org/load/f3c8c4aad023615382282a653efb8b4728f80f6c5fe025d42c972b30465d6cb4'
2. Click on 'Topoligical Object Event FRM under HEK'

**Expected behavior**
Markers should be shown

### LINKED ISSUE #589: [User Bug Report] - SPoCA active regions and coronal holes being highlighted simultaneously
When I deselect all HEK, then select SPoCA AR and SPoCA CH, then when I mouseover either "SPoCA" under "Active Region" or "SPoCA" under "Coronal Hole" then both active region and coronal hole results are highlighted. I'd expect only the one I mouseover'd to be highlighted.

See
https://helioviewer.org/load/d51cc721ae71ca02118406df2f81c8d21ea8a284ec457ba5186c8b41bd780de4

### PR DESCRIPTION
**Pull request by mudhoney**
# Summary

Fix #588 
Fix #589 

# Testing

Implemented playwright tests

### CODE REVIEW

File: resources/js/Events/EventManager.js [hunk 1]
```diff
@@ -429,12 +429,16 @@ var EventManager = Class.extend({
                     checkedFRMs[checkedTypeObj['event_type']].push(parsedFrm);
                 }
 
-                // If we haven't already seen frm , in our fake frm and childrens data, define it 
-                // or add it
-                if(!notFullySelectedFRMSAndChildrens.hasOwnProperty(parsedFrm)) {
-                    notFullySelectedFRMSAndChildrens[parsedFrm] = [eventInstanceNewName];
+                // If there is no event_type to host frms and their children, we create it
+                if(!notFullySelectedFRMSAndChildrens.hasOwnProperty(checkedTypeObj['event_type'])) {
```
Comment (dgarciabriseno) [inline resources/js/Events/EventManager.js:433]: `
let event_type = checkedTypeObj['event_type'];
`

File: tests/page_objects/event_tree.ts [hunk 2]
```diff
@@ -0,0 +1,278 @@
...
+    **/
+    async assertEventInstanceTreeNodeVisible(event_type:string, frm: string, event_instance: string) {
+
+        const eventTypeLink = this.page.getByRole('link', {name: event_type});
+        const eventTypeNode = await this.root.getByRole('listitem').filter({has: eventTypeLink});
+
+        const eventFRMLink = this.page.getByRole('link', {name: frm});
+        const eventFRMNode = await eventTypeNode.getByRole('listitem').filter({has: eventFRMLink});
+
+        expect (eventFRMNode.getByRole('link', {name: event_instance})).toBeVisible();
```
Comment (dgarciabriseno) [inline tests/page_objects/event_tree.ts:167]:
```suggestion
        await expect (eventFRMNode.getByRole('link', {name: event_instance})).toBeVisible();
```

File: tests/page_objects/event_tree.ts [hunk 3]
```diff
@@ -0,0 +1,278 @@
...
+    **/
+    async assertEventInstanceTreeNodeNotVisible(event_type:string, frm: string, event_instance: string) {
+
+        const eventTypeLink = this.page.getByRole('link', {name: event_type});
+        const eventTypeNode = await this.root.getByRole('listitem').filter({has: eventTypeLink});
+
+        const eventFRMLink = this.page.getByRole('link', {name: frm});
+        const eventFRMNode = await eventTypeNode.getByRole('listitem').filter({has: eventFRMLink});
+
+        expect (eventFRMNode.getByRole('link', {name: event_instance})).not.toBeVisible();
```
Comment (dgarciabriseno) [inline tests/page_objects/event_tree.ts:185]:
```suggestion
        await expect(eventFRMNode.getByRole('link', {name: event_instance})).not.toBeVisible();
```

File: tests/page_objects/event_tree.ts [hunk 4]
```diff
@@ -0,0 +1,278 @@
...
+        await eventFRMNode.getByRole('link', {name: event_instance}).hover();
+    }
+
+    /**
+    * This function asserts if the marker for given event_instance is visible 
+    * @param event_instance parameter specifies the name of the event instance (ex: "NOAA 12674 β"). 
+    * @return void promise about the assertion is done
+    **/
+    async assertMarkerVisible(event_instance: string) {
+        expect (await this.markersRoot.getByText(event_instance)).toBeVisible();
```
Comment (dgarciabriseno) [inline tests/page_objects/event_tree.ts:241]:
```suggestion
        await expect(await this.markersRoot.getByText(event_instance)).toBeVisible();
```

File: tests/page_objects/event_tree.ts [hunk 5]
```diff
@@ -0,0 +1,278 @@
...
+
+    /**
+    * This function asserts if the marker for given event_instance is visible but it is NOT highlighted 
+    * @param event_instance parameter specifies the name of the event instance (ex: "NOAA 12674 β"). 
+    * @return void promise about the assertion is done
+    **/
+    async assertMarkerNotHighlighted(event_instance: string) {
+        const markerLabel = await this.markersRoot.getByText(event_instance);
+        expect (markerLabel).toBeVisible();
+        expect (markerLabel).not.toHaveClass('event-label event-label-hover');
```
Comment (dgarciabriseno) [inline tests/page_objects/event_tree.ts:273]:
```suggestion
        await expect (markerLabel).toBeVisible();
        await expect (markerLabel).not.toHaveClass('event-label event-label-hover');
```

**Review by dgarciabriseno — APPROVED** [review]
