### PR TITLE
Third level control on feature and events tree with new hovering effects

### LINKED ISSUE #543: Unexpected removal of pins for hovered checkboxes for features and events
**Describe the bug**

**To Reproduce**
1. Go to '[heiloviewer](https://www.helioviewer.org/)'
2. Scrool Down to `Features and Events > CCMC`
3. `DONKI` tree item is checked by default with all its childrens `CME` and `Solar Flares`
4. Uncheck just `CME`
5. All pins gone

**Expected behavior**
Heiloviewer should still show pins belong to `DONKI` and all its children including `Solar Flares`. Ideally hovering on those checkboxes should not affect which pins are being shown on screen, it should set bolder texts if checkbox is hovered, that might bring more intiuative ui experience for the users of heiloviewer

**Screenshots**
first_all_pins
second_ping

### PR DESCRIPTION
**Pull request by mudhoney**
# Summary

- Fixes #543 
- Implements #265 

- implement 3rd level of feature and events tree
- make event cache system to work with current state
- new hovered emphasize mechanism for frms and event_instances
- fix small bug about remembering feature and event states
- change localStorage events keys for current sessions

# Testing

Enter the browser versions this change was tested on below.

| browser | version  |
| ------- | -------- |
| firefox | tested|
| chrome  | tested |
| safari  | tested|
| edge    | tested|

### CODE REVIEW

File: resources/js/Events/EventManager.js [hunk 1]
```diff
@@ -227,9 +241,13 @@ var EventManager = Class.extend({
                 event_type_arr[0] = event_type_arr[0].slice(0,-1);
             }
 
+            // console.log(event_type_arr);
```
Comment (dgarciabriseno) [inline resources/js/Events/EventManager.js]: remove this line

File: resources/js/Events/EventManager.js [hunk 2]
```diff
@@ -240,18 +258,30 @@ var EventManager = Class.extend({
                 let group_count = group.data.length;
                 type_count += group_count;
 
+                // Generate event instances nodes for jstree
+                let group_children = group.data.map(d => {
+                    return {
+                        'data': d.label,
```
Comment (dgarciabriseno) [inline resources/js/Events/EventManager.js]: is `d` here the event data?

Change this to `d.short_label  ?? d.label`

I originally intended for `label` to be what you see next to the pin, so the text is long.
I can add `short_label` to the event data later on to have something that looks better in the sidebar.

**Review by dgarciabriseno — CHANGES_REQUESTED** [review]

File: resources/js/Events/EventManager.js (hunk 2 above)
Comment (mudhoney) [reply resources/js/Events/EventManager.js]: Yes make sense, will do that, 
Also thank you! for the `??` operator, I didn't know that

**Review by dgarciabriseno — APPROVED** [review]
